### ISSUE TITLE
RecordMutex::Lock和Unlock可能有个race condition

### ISSUE THREAD

**Issue by DavidLiuXh** [PikaLabs/slash#8]
在Unlock中 ref_mutex->Unref();中delete了这个RefMutex后, 在Lock中是不是可能调用ref_mutex->Lock()?

**Comment by gaodq** [comment]
https://github.com/Qihoo360/slash/blob/95c3c6313b7b360490cd5d6673f2519e48452c4f/slash/src/slash_mutex.cc#L178-L180
如果是最后一个引用就从`records_`中删除了
在Lock里面也就不会找到这个ref_mutex了

**Comment by DavidLiuXh** [comment]
map的锁在是ref_mutex->Lock()之前被 unlock的, 理伦上还是有可能先earse + unref后又调用了Lock

**Comment by gaodq** [comment]
确实会。。额

**Comment by gaodq** [comment]
Lock()、Unlock()一般是在同一线程中按顺序使用，现实中不会发生Unlock(key)在Lock(key)之前的情况。

**Comment by KernelMaker** [comment]
@DavidLiuXh 我擦，老司机看slash，硬广：推荐看https://github.com/KernelMaker/rocksutil

**Comment by DavidLiuXh** [comment]
@KernelMaker 本来打算打Pink, 发现里面还用了slash

**Comment by DavidLiuXh** [comment]
@gaodq 公共接口的没法预测是不是在同一线程里, 要是同一线程应该都不用lock了吧.

**Comment by gaodq** [comment]
一个线程里的lock unlock操作不都应该是成对出现的吗

**Comment by DavidLiuXh** [comment]
@gaodq 没错, 所以在lock unlock这个操作可能同时出现在两个thread里,理伦上还是有可能先earse + unref后又调用了Lock

**Comment by gaodq** [comment]
ref_mutex指向的是一个key的锁，如果是同一个key，在两个thread里操作不会有问题，因为都是先lock；如果是不同的key那更不会存在问题了，因为操作的是不同的ref_mutex
